language: go
cache:
  directories:
    - ${GOPATH}/src/github.com/${TRAVIS_REPO_SLUG}/vendor
    - ${GOPATH}/src/github.com/golang
    - ${GOPATH}/src/github.com/mattn
    - ${GOPATH}/src/golang.org/x
    - ${GOPATH}/src/honnef.co
go:
  - "1.13"

script:
  - make ci
